# Sprint 2.1 – Dataset Loading and File Handling

## AI/ML Engineer Training Program

### Engineer
**Apuri Saikumar**

---

## Sprint Objective

The objective of this sprint is to understand dataset loading, file handling, logging, exception handling, and dataset writing using Python.

This notebook demonstrates how to work with different dataset formats such as CSV, Excel, JSON, and Text files while following software engineering best practices including modular programming, reusable functions, proper logging, and exception handling.

---

### Technologies Used

- Python 3.12
- Pandas
- OpenPyXL
- JSON
- Logging
- Pathlib
- Pickle
- Jupyter Notebook

# Sprint Objectives

In this notebook we will learn how to:

- Load datasets from multiple file formats.
- Read CSV files using different configurations.
- Read Excel workbooks and worksheets.
- Read nested JSON files.
- Read Text files.
- Save datasets in different formats.
- Manage file paths efficiently.
- Configure logging.
- Implement custom exception handling.
- Write modular and reusable Python code.

# Implementation Workflow

The notebook has been organized into independent modules.

```
Project Workflow

Dataset
    │
    ▼
File Validation
    │
    ▼
CSV / Excel / JSON / TXT Loader
    │
    ▼
Dataset Processing
    │
    ▼
Dataset Writer
    │
    ▼
Logging
    │
    ▼
Exception Handling
```

Each module is implemented independently to improve readability, maintainability, and reusability.

# Environment Setup

Before loading any datasets, we configure the notebook environment by importing all required libraries.

The imported libraries provide support for:

- Reading different dataset formats
- File and directory management
- Logging
- Exception handling
- Data serialization
- Working with paths

In [3]:
import os
import json
import pickle
import logging
from pathlib import Path

import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [4]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)
pd.set_option("display.width", 1000)

print("Environment configured successfully.")

Environment configured successfully.

In [5]:
BASE_DIR = Path.cwd().parent

DATASET_DIR = BASE_DIR / "datasets"

OUTPUT_DIR = BASE_DIR / "outputs"

LOG_DIR = BASE_DIR / "logs"

print("Dataset Folder :", DATASET_DIR)
print("Output Folder  :", OUTPUT_DIR)
print("Logs Folder    :", LOG_DIR)

Dataset Folder : c:\Users\apuri\sprint2_dataset_loading\datasets
Output Folder  : c:\Users\apuri\sprint2_dataset_loading\outputs
Logs Folder    : c:\Users\apuri\sprint2_dataset_loading\logs

In [6]:
OUTPUT_DIR.mkdir(exist_ok=True)

LOG_DIR.mkdir(exist_ok=True)

print("Project directories verified.")

Project directories verified.

# Module 7 – Logging Configuration

## Purpose

Logging is an essential software engineering practice that helps monitor application execution, debug issues, and maintain an execution history.

In this notebook, logging is configured to:

- Track file loading operations
- Track file writing operations
- Record warning and error messages
- Capture exception details
- Store logs in `logs/application.log`

This centralized logging mechanism improves traceability and simplifies debugging.

In [9]:
import logging

LOG_FILE = LOG_DIR / "application.log"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler()
    ],
    force=True
)

logger = logging.getLogger(__name__)

logger.info("Logging configured successfully.")

2026-07-01 18:43:01,589 | INFO | Logging configured successfully.

In [10]:
logger.info("Dataset loading started.")

logger.warning("This is a sample warning message.")

logger.error("This is a sample error message.")

2026-07-01 18:44:05,739 | INFO | Dataset loading started.
2026-07-01 18:44:05,741 | WARNING | This is a sample warning message.
2026-07-01 18:44:05,742 | ERROR | This is a sample error message.

# Module 8 – Custom Exception Handling

## Purpose

Exception handling ensures that the notebook can gracefully handle unexpected situations such as:

- Missing files
- Invalid file formats
- Corrupted datasets
- Invalid worksheet names
- Incorrect file paths

Instead of displaying generic Python exceptions, meaningful custom exceptions are created to improve debugging and readability.

In [12]:
class DatasetLoadingException(Exception):
    """
    Base exception for dataset loading errors.
    """
    pass


class InvalidFilePathException(DatasetLoadingException):
    """
    Raised when the file path is invalid.
    """
    pass


class UnsupportedFileFormatException(DatasetLoadingException):
    """
    Raised when an unsupported file format is used.
    """
    pass


class InvalidWorksheetException(DatasetLoadingException):
    """
    Raised when an Excel worksheet does not exist.
    """
    pass


class CorruptedFileException(DatasetLoadingException):
    """
    Raised when a file is corrupted.
    """
    pass

In [13]:
try:
    raise InvalidFilePathException(
        "Dataset path does not exist."
    )

except InvalidFilePathException as error:
    logger.error(error)
    print(error)

2026-07-01 18:52:48,799 | ERROR | Dataset path does not exist.

Dataset path does not exist.

In [14]:
try:
    raise UnsupportedFileFormatException(
        "XML files are not supported."
    )

except UnsupportedFileFormatException as error:
    logger.error(error)
    print(error)

2026-07-01 18:53:15,089 | ERROR | XML files are not supported.

XML files are not supported.

# Module 1 – CSV Dataset Loader

## Purpose

CSV (Comma Separated Values) is one of the most commonly used dataset formats in Data Science and Machine Learning.

Before any preprocessing or model building, datasets are usually loaded into a Pandas DataFrame.

This module demonstrates:

- Reading CSV datasets
- Reading CSV using custom delimiters
- Supporting different file encodings
- Reading large CSV files
- Validating file paths
- Handling corrupted CSV files
- Logging every operation
- Exception handling

In [15]:
csv_file = DATASET_DIR / "employees.csv"

print(csv_file)

c:\Users\apuri\sprint2_dataset_loading\datasets\employees.csv

In [16]:
if csv_file.exists():
    logger.info("CSV file found.")
    print("CSV file exists.")

else:
    logger.error("CSV file not found.")
    raise InvalidFilePathException(
        f"{csv_file} does not exist."
    )

2026-07-01 22:39:58,386 | INFO | CSV file found.

CSV file exists.

In [17]:
try:

    logger.info("Loading CSV file.")

    employees_df = pd.read_csv(csv_file)

    logger.info("CSV loaded successfully.")

    print("Dataset Loaded Successfully")

    display(employees_df.head())

except Exception as error:

    logger.error(error)

    raise CorruptedFileException(
        "Unable to read CSV file."
    )

2026-07-01 22:40:28,126 | INFO | Loading CSV file.
2026-07-01 22:40:28,265 | INFO | CSV loaded successfully.

Dataset Loaded Successfully

   CustomerID                 Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001       Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002        Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02
2        1003       Anthony Nelson   32    Male  Chennai   78351         IT           3  2020-01-03
3        1004         Derek Martin   60    Male  Chennai   86267    Finance           1  2020-01-04
4        1005  Jeffrey Stevens DVM   25    Male  Madurai   73354         HR           1  2020-01-05

In [18]:
print("Shape:", employees_df.shape)

print()

print("Columns")

display(employees_df.columns)

print()

print("Data Types")

display(employees_df.dtypes)

Shape: (100, 9)

Columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Department', 'Experience', 'JoiningDate'], dtype='object')

Data Types

CustomerID      int64
Name           object
Age             int64
Gender         object
City           object
Salary          int64
Department     object
Experience      int64
JoiningDate    object
dtype: object

In [19]:
display(
    employees_df.isnull().sum()
)

CustomerID     0
Name           0
Age            0
Gender         0
City           0
Salary         0
Department     0
Experience     0
JoiningDate    0
dtype: int64

In [20]:
try:

    delimiter_df = pd.read_csv(
        csv_file,
        delimiter=","
    )

    print("Custom delimiter loaded successfully.")

    display(delimiter_df.head())

except Exception as error:

    logger.error(error)

Custom delimiter loaded successfully.

   CustomerID                 Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001       Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002        Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02
2        1003       Anthony Nelson   32    Male  Chennai   78351         IT           3  2020-01-03
3        1004         Derek Martin   60    Male  Chennai   86267    Finance           1  2020-01-04
4        1005  Jeffrey Stevens DVM   25    Male  Madurai   73354         HR           1  2020-01-05

In [21]:
utf_df = pd.read_csv(
    csv_file,
    encoding="utf-8"
)

display(
    utf_df.head()
)

   CustomerID                 Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001       Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002        Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02
2        1003       Anthony Nelson   32    Male  Chennai   78351         IT           3  2020-01-03
3        1004         Derek Martin   60    Male  Chennai   86267    Finance           1  2020-01-04
4        1005  Jeffrey Stevens DVM   25    Male  Madurai   73354         HR           1  2020-01-05

In [22]:
chunk_size = 2

for chunk in pd.read_csv(
    csv_file,
    chunksize=chunk_size
):

    display(chunk)

   CustomerID            Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001  Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002   Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02

   CustomerID            Name  Age Gender     City  Salary Department  Experience JoiningDate
2        1003  Anthony Nelson   32   Male  Chennai   78351         IT           3  2020-01-03
3        1004    Derek Martin   60   Male  Chennai   86267    Finance           1  2020-01-04

   CustomerID                 Name  Age Gender     City  Salary Department  Experience JoiningDate
4        1005  Jeffrey Stevens DVM   25   Male  Madurai   73354         HR           1  2020-01-05
5        1006         James Miller   38   Male  Chennai   27557         IT          19  2020-01-06

   CustomerID           Name  Age  Gender    City  Salary Department  Experience JoiningDate
6        1007   Chad Burgess   56  Female   Salem   63360  Marketing          11  2020-01-07
7        1008  Kristy Walker   36    Male  Trichy  107018         IT           5  2020-01-08

   CustomerID           Name  Age Gender     City  Salary Department  Experience JoiningDate
8        1009  Donna Hickman   40   Male  Chennai   27200         HR          12  2020-01-09
9        1010   Patrick Dyer   28   Male  Madurai   93497         IT           3  2020-01-10

    CustomerID          Name  Age Gender     City  Salary Department  Experience JoiningDate
10        1011  John Lambert   28   Male  Madurai   71975      Sales           1  2020-01-11
11        1012    David Wood   41   Male  Chennai   46357         IT           1  2020-01-12

    CustomerID           Name  Age  Gender     City  Salary Department  Experience JoiningDate
12        1013  Michelle Moss   53  Female   Trichy  102505    Finance           8  2020-01-13
13        1014   Andrew Jones   57    Male  Chennai   27869    Finance          10  2020-01-14

    CustomerID               Name  Age  Gender        City  Salary Department  Experience JoiningDate
14        1015     George Edwards   41  Female     Madurai   86135      Sales          11  2020-01-15
15        1016  Matthew Stevenson   20    Male  Coimbatore   75108         HR          12  2020-01-16

    CustomerID        Name  Age  Gender     City  Salary Department  Experience JoiningDate
16        1017  Shaun Hess   39  Female    Salem  119179    Finance          13  2020-01-17
17        1018  Evan Garza   19    Male  Madurai  115272  Marketing          12  2020-01-18

    CustomerID            Name  Age  Gender     City  Salary Department  Experience JoiningDate
18        1019    Ashley Smith   41    Male  Chennai   63467    Finance          14  2020-01-19
19        1020  Jeremy Douglas   61  Female    Salem   48328    Finance           2  2020-01-20

    CustomerID            Name  Age  Gender     City  Salary Department  Experience JoiningDate
20        1021  Jamie Valencia   47  Female  Chennai  116412         HR          19  2020-01-21
21        1022     Andrea Todd   55  Female  Chennai  111831         IT          18  2020-01-22

    CustomerID          Name  Age  Gender        City  Salary Department  Experience JoiningDate
22        1023  Denise Watts   19    Male  Coimbatore   28987    Finance           3  2020-01-23
23        1024  Jorge Garner   38  Female       Salem   83871      Sales          17  2020-01-24

    CustomerID            Name  Age Gender        City  Salary Department  Experience JoiningDate
24        1025     Jacob Brown   50   Male       Salem   47399         IT           8  2020-01-25
25        1026  Jordan Calhoun   29   Male  Coimbatore   71214  Marketing          10  2020-01-26

    CustomerID              Name  Age  Gender     City  Salary Department  Experience JoiningDate
26        1027  Colleen Gonzalez   39  Female  Madurai  111416         HR           2  2020-01-27
27        1028       Guy Goodwin   61  Female  Chennai   95271  Marketing          19  2020-01-28

    CustomerID              Name  Age Gender     City  Salary Department  Experience JoiningDate
28        1029  Nancy Massey DVM   42   Male   Trichy   69064         IT           9  2020-01-29
29        1030       Jason White   44   Male  Chennai   95091         IT           7  2020-01-30

    CustomerID                Name  Age  Gender     City  Salary Department  Experience JoiningDate
30        1031            Aaron Le   59  Female  Chennai   65818         IT           4  2020-01-31
31        1032  Mr. James Richards   45  Female  Madurai   70525  Marketing          18  2020-02-01

    CustomerID            Name  Age  Gender        City  Salary Department  Experience JoiningDate
32        1033  Kaylee Beltran   33  Female     Chennai   44830         IT          13  2020-02-02
33        1034   Samantha Wood   32    Male  Coimbatore   42429  Marketing          11  2020-02-03

    CustomerID           Name  Age Gender        City  Salary Department  Experience JoiningDate
34        1035    Autumn King   64   Male  Coimbatore   31893         IT           4  2020-02-04
35        1036  Ashley Brewer   61   Male       Salem  104909      Sales           4  2020-02-05

    CustomerID          Name  Age Gender     City  Salary Department  Experience JoiningDate
36        1037   Sarah Baker   20   Male   Trichy   72333         IT          10  2020-02-06
37        1038  Julia Nelson   54   Male  Chennai   28436  Marketing           5  2020-02-07

    CustomerID             Name  Age  Gender     City  Salary Department  Experience JoiningDate
38        1039  Dr. Bruce Perez   24    Male  Chennai   99290    Finance           9  2020-02-08
39        1040   Ashley Marquez   38  Female  Madurai  101213         IT           3  2020-02-09

    CustomerID              Name  Age Gender        City  Salary Department  Experience JoiningDate
40        1041  Jennifer Sanders   26   Male  Coimbatore   30895    Finance          17  2020-02-10
41        1042    Wesley Woodard   56   Male      Trichy   44738      Sales           3  2020-02-11

    CustomerID            Name  Age  Gender        City  Salary Department  Experience JoiningDate
42        1043     Scott White   35    Male       Salem   55746         HR          16  2020-02-12
43        1044  Andrea Compton   21  Female  Coimbatore   74377      Sales           4  2020-02-13

    CustomerID           Name  Age Gender     City  Salary Department  Experience JoiningDate
44        1045   Steven Giles   42   Male    Salem   73404         IT          18  2020-02-14
45        1046  Lynn Johnston   31   Male  Madurai   79045    Finance          17  2020-02-15

    CustomerID               Name  Age  Gender     City  Salary Department  Experience JoiningDate
46        1047      Valerie Smith   26  Female  Madurai   64790    Finance           7  2020-02-16
47        1048  Kimberly Anderson   43    Male  Chennai   30600  Marketing           5  2020-02-17

    CustomerID            Name  Age Gender    City  Salary Department  Experience JoiningDate
48        1049   Julie Stewart   19   Male  Trichy  119660    Finance          12  2020-02-18
49        1050  Peter Trujillo   37   Male   Salem  118179  Marketing          17  2020-02-19

    CustomerID             Name  Age Gender        City  Salary Department  Experience JoiningDate
50        1051      James Jones   45   Male  Coimbatore   65764         HR          13  2020-02-20
51        1052  Michelle Bailey   64   Male     Madurai   99543         IT           3  2020-02-21

    CustomerID            Name  Age  Gender     City  Salary Department  Experience JoiningDate
52        1053    Keith Nguyen   24  Female  Chennai   70714  Marketing           9  2020-02-22
53        1054  John Hernandez   61  Female  Chennai   81835         HR          17  2020-02-23

    CustomerID           Name  Age  Gender     City  Salary Department  Experience JoiningDate
54        1055  Blake Salazar   25  Female    Salem   98744    Finance          17  2020-02-24
55        1056   Aaron Wagner   64    Male  Madurai   81491    Finance          16  2020-02-25

    CustomerID           Name  Age Gender     City  Salary Department  Experience JoiningDate
56        1057  James Douglas   52   Male   Trichy   43589         HR          13  2020-02-26
57        1058      Seth Bush   31   Male  Madurai   68484    Finance          19  2020-02-27

    CustomerID             Name  Age  Gender   City  Salary Department  Experience JoiningDate
58        1059    David Trevino   34  Female  Salem  107989         HR          17  2020-02-28
59        1060  Jennifer Martin   53    Male  Salem   61212  Marketing           4  2020-02-29

    CustomerID            Name  Age  Gender     City  Salary Department  Experience JoiningDate
60        1061  Jeffrey Newman   57    Male  Madurai   68525  Marketing          12  2020-03-01
61        1062     Dennis Mata   21  Female    Salem   72202         HR           9  2020-03-02

    CustomerID           Name  Age  Gender        City  Salary Department  Experience JoiningDate
62        1063  Anthony Hardy   19    Male     Madurai   57635  Marketing          19  2020-03-03
63        1064   Mark Sanchez   23  Female  Coimbatore   88208  Marketing          12  2020-03-04

    CustomerID               Name  Age  Gender     City  Salary Department  Experience JoiningDate
64        1065     Jennifer Bates   59  Female  Madurai   58828  Marketing           9  2020-03-05
65        1066  Mr. Lucas Nichols   21  Female  Madurai   43711      Sales           7  2020-03-06

    CustomerID              Name  Age Gender   City  Salary Department  Experience JoiningDate
66        1067      John Ferrell   46   Male  Salem   28420         IT          14  2020-03-07
67        1068  Sierra Patterson   35   Male  Salem   25301    Finance          19  2020-03-08

    CustomerID             Name  Age Gender     City  Salary Department  Experience JoiningDate
68        1069  Jonathan Briggs   43   Male  Chennai   70236      Sales          15  2020-03-09
69        1070    Tanner Martin   61   Male  Chennai   91235  Marketing          16  2020-03-10

    CustomerID           Name  Age Gender        City  Salary Department  Experience JoiningDate
70        1071  Matthew Smith   51   Male  Coimbatore   79240         HR           5  2020-03-11
71        1072   David Holmes   27   Male     Chennai   90726  Marketing           3  2020-03-12

    CustomerID            Name  Age  Gender     City  Salary Department  Experience JoiningDate
72        1073  Jonathan Burns   53    Male  Madurai   35492         IT          12  2020-03-13
73        1074   Hannah Sparks   31  Female    Salem   31102  Marketing           4  2020-03-14

    CustomerID            Name  Age  Gender     City  Salary Department  Experience JoiningDate
74        1075  David Gonzalez   48    Male  Chennai   75336         HR          16  2020-03-15
75        1076    Mary Johnson   32  Female  Chennai  110314         IT           7  2020-03-16

    CustomerID             Name  Age Gender        City  Salary Department  Experience JoiningDate
76        1077  Rebecca Bradley   25   Male  Coimbatore   51641  Marketing          13  2020-03-17
77        1078    Emily Collins   31   Male  Coimbatore   59584         IT          10  2020-03-18

    CustomerID             Name  Age  Gender     City  Salary Department  Experience JoiningDate
78        1079    Debra Sherman   40    Male  Madurai   57745    Finance           7  2020-03-19
79        1080  Michael Mahoney   57  Female    Salem   48093    Finance          14  2020-03-20

    CustomerID                 Name  Age  Gender        City  Salary Department  Experience JoiningDate
80        1081  Patricia Richardson   38  Female  Coimbatore   91105  Marketing           5  2020-03-21
81        1082          Ashley Mora   33  Female     Chennai   76885         IT           3  2020-03-22

    CustomerID              Name  Age  Gender   City  Salary Department  Experience JoiningDate
82        1083      Meghan Gomez   62  Female  Salem   61631         HR          11  2020-03-23
83        1084  Christine Deleon   35    Male  Salem   97991  Marketing          11  2020-03-24

    CustomerID          Name  Age  Gender        City  Salary Department  Experience JoiningDate
84        1085    Eric Allen   64  Female     Chennai   29014    Finance          18  2020-03-25
85        1086  Phillip York   41    Male  Coimbatore   36093    Finance          15  2020-03-26

    CustomerID         Name  Age  Gender     City  Salary Department  Experience JoiningDate
86        1087   John Bryan   43    Male  Chennai   43070  Marketing          12  2020-03-27
87        1088  Dawn Bryant   42  Female    Salem   60777         IT           9  2020-03-28

    CustomerID              Name  Age  Gender    City  Salary Department  Experience JoiningDate
88        1089  Daniel Contreras   62  Female  Trichy   81958    Finance          10  2020-03-29
89        1090    Sarah Martinez   58  Female  Trichy  107074         IT          12  2020-03-30

    CustomerID          Name  Age  Gender     City  Salary Department  Experience JoiningDate
90        1091  Nancy Chavez   46  Female  Madurai   35729    Finance          17  2020-03-31
91        1092   Amy Sanchez   32  Female  Chennai   70017    Finance           6  2020-04-01

    CustomerID          Name  Age  Gender     City  Salary Department  Experience JoiningDate
92        1093  Brett Barnes   62  Female  Chennai   91320      Sales           7  2020-04-02
93        1094   Jesse Myers   18  Female  Madurai   52751    Finance          14  2020-04-03

    CustomerID            Name  Age  Gender     City  Salary Department  Experience JoiningDate
94        1095  Stephen Hodges   42  Female  Madurai  103069         HR          13  2020-04-04
95        1096   Leslie Torres   24    Male  Madurai   79748  Marketing           8  2020-04-05

    CustomerID          Name  Age  Gender     City  Salary Department  Experience JoiningDate
96        1097   Jason Mills   26  Female    Salem   30801  Marketing          10  2020-04-06
97        1098  Kelly Potter   41  Female  Chennai   44190         IT           9  2020-04-07

    CustomerID              Name  Age  Gender     City  Salary Department  Experience JoiningDate
98        1099      Todd Simmons   18    Male    Salem   74689    Finance          18  2020-04-08
99        1100  Catherine Spence   61  Female  Madurai   75993         HR           2  2020-04-09

In [23]:
try:

    pd.read_csv(
        DATASET_DIR / "missing.csv"
    )

except FileNotFoundError as error:

    logger.error(error)

    print(error)

2026-07-01 22:43:29,945 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.csv'

[Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.csv'

## Module Summary

Successfully implemented:

- CSV loading
- File validation
- Custom delimiter
- UTF-8 encoding
- Chunk processing
- Logging
- Exception handling

This implementation satisfies all CSV loading requirements specified in Sprint 2.

# Module 2 – Excel Dataset Loader

## Purpose

Microsoft Excel is one of the most commonly used formats for storing structured business data.

Unlike CSV files, Excel files can contain multiple worksheets in a single workbook.

This module demonstrates:

- Reading Excel workbooks
- Listing available worksheets
- Reading specific worksheets
- Reading all worksheets
- Handling invalid worksheet names
- Exception handling
- Logging every operation

In [24]:
excel_file = DATASET_DIR / "employees.xlsx"

print("Excel File :", excel_file)

Excel File : c:\Users\apuri\sprint2_dataset_loading\datasets\employees.xlsx

In [25]:
if excel_file.exists():

    logger.info("Excel file found.")

    print("Excel file exists.")

else:

    logger.error("Excel file not found.")

    raise InvalidFilePathException(
        f"{excel_file} does not exist."
    )

2026-07-01 22:46:35,070 | INFO | Excel file found.

Excel file exists.

In [26]:
try:

    logger.info("Loading Excel workbook.")

    excel_df = pd.read_excel(excel_file)

    logger.info("Excel loaded successfully.")

    print("Excel Dataset Loaded Successfully")

    display(excel_df.head())

except Exception as error:

    logger.error(error)

    raise CorruptedFileException(
        "Unable to read Excel file."
    )

2026-07-01 22:46:53,669 | INFO | Loading Excel workbook.
2026-07-01 22:46:54,559 | INFO | Excel loaded successfully.

Excel Dataset Loaded Successfully

   CustomerID                 Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001       Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002        Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02
2        1003       Anthony Nelson   32    Male  Chennai   78351         IT           3  2020-01-03
3        1004         Derek Martin   60    Male  Chennai   86267    Finance           1  2020-01-04
4        1005  Jeffrey Stevens DVM   25    Male  Madurai   73354         HR           1  2020-01-05

In [27]:

workbook = pd.ExcelFile(excel_file)

print("Available Worksheets")

display(workbook.sheet_names)

Available Worksheets

['Employees', 'Top20']

In [28]:
employee_sheet = pd.read_excel(
    excel_file,
    sheet_name="Employees"
)

display(employee_sheet.head())

   CustomerID                 Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001       Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002        Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02
2        1003       Anthony Nelson   32    Male  Chennai   78351         IT           3  2020-01-03
3        1004         Derek Martin   60    Male  Chennai   86267    Finance           1  2020-01-04
4        1005  Jeffrey Stevens DVM   25    Male  Madurai   73354         HR           1  2020-01-05

In [29]:
all_sheets = pd.read_excel(
    excel_file,
    sheet_name=None
)

print("Total Worksheets :", len(all_sheets))

for sheet_name, dataframe in all_sheets.items():

    print(f"\nWorksheet : {sheet_name}")

    display(dataframe.head())

Total Worksheets : 2

Worksheet : Employees

   CustomerID                 Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001       Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002        Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02
2        1003       Anthony Nelson   32    Male  Chennai   78351         IT           3  2020-01-03
3        1004         Derek Martin   60    Male  Chennai   86267    Finance           1  2020-01-04
4        1005  Jeffrey Stevens DVM   25    Male  Madurai   73354         HR           1  2020-01-05

Worksheet : Top20

   CustomerID                 Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001       Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002        Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02
2        1003       Anthony Nelson   32    Male  Chennai   78351         IT           3  2020-01-03
3        1004         Derek Martin   60    Male  Chennai   86267    Finance           1  2020-01-04
4        1005  Jeffrey Stevens DVM   25    Male  Madurai   73354         HR           1  2020-01-05

In [30]:
try:

    pd.read_excel(
        excel_file,
        sheet_name="InvalidSheet"
    )

except ValueError as error:

    logger.error(error)

    print(error)

2026-07-01 22:49:42,200 | ERROR | Worksheet named 'InvalidSheet' not found

Worksheet named 'InvalidSheet' not found

In [31]:
try:

    pd.read_excel(
        DATASET_DIR / "missing.xlsx"
    )

except FileNotFoundError as error:

    logger.error(error)

    print(error)

2026-07-01 22:50:05,446 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.xlsx'

[Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.xlsx'

In [32]:
print("Shape :", excel_df.shape)

print()

print("Columns")

display(excel_df.columns)

print()

print("Data Types")

display(excel_df.dtypes)

Shape : (100, 9)

Columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Department', 'Experience', 'JoiningDate'], dtype='object')

Data Types

CustomerID      int64
Name           object
Age             int64
Gender         object
City           object
Salary          int64
Department     object
Experience      int64
JoiningDate    object
dtype: object

## Module Summary

Successfully implemented:

- Reading Excel workbooks
- Reading specific worksheets
- Reading all worksheets
- Listing worksheet names
- File validation
- Logging
- Exception handling

This implementation satisfies all Excel loading requirements specified in Sprint 2.

# Module 3 – JSON Dataset Loader

## Purpose

JSON (JavaScript Object Notation) is one of the most widely used data exchange formats in APIs, cloud applications, and machine learning pipelines.

Unlike CSV files, JSON supports hierarchical and nested structures, making it ideal for representing complex datasets.

This module demonstrates:

- Reading JSON files
- Loading nested JSON data
- Handling invalid JSON formats
- Handling missing files
- Logging every operation
- Exception handling

In [33]:
json_file = DATASET_DIR / "employees.json"

print("JSON File :", json_file)

JSON File : c:\Users\apuri\sprint2_dataset_loading\datasets\employees.json

In [34]:
if json_file.exists():

    logger.info("JSON file found.")

    print("JSON file exists.")

else:

    logger.error("JSON file not found.")

    raise InvalidFilePathException(
        f"{json_file} does not exist."
    )

2026-07-01 23:30:09,170 | INFO | JSON file found.

JSON file exists.

In [35]:
try:

    logger.info("Loading JSON dataset.")

    json_df = pd.read_json(json_file)

    logger.info("JSON loaded successfully.")

    print("JSON Dataset Loaded Successfully")

    display(json_df.head())

except ValueError as error:

    logger.error(error)

    raise CorruptedFileException(
        "Invalid JSON format."
    )

except Exception as error:

    logger.error(error)

    raise

2026-07-01 23:30:30,713 | INFO | Loading JSON dataset.
2026-07-01 23:30:30,809 | INFO | JSON loaded successfully.

JSON Dataset Loaded Successfully

   CustomerID                 Name  Age  Gender     City  Salary Department  Experience JoiningDate
0        1001       Martin Jackson   56  Female  Chennai   57711         HR          12  2020-01-01
1        1002        Matthew Lopez   46  Female  Chennai   30539  Marketing          18  2020-01-02
2        1003       Anthony Nelson   32    Male  Chennai   78351         IT           3  2020-01-03
3        1004         Derek Martin   60    Male  Chennai   86267    Finance           1  2020-01-04
4        1005  Jeffrey Stevens DVM   25    Male  Madurai   73354         HR           1  2020-01-05

In [36]:
print("Shape :", json_df.shape)

print()

print("Columns")

display(json_df.columns)

print()

print("Data Types")

display(json_df.dtypes)

Shape : (100, 9)

Columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Department', 'Experience', 'JoiningDate'], dtype='object')

Data Types

CustomerID      int64
Name           object
Age             int64
Gender         object
City           object
Salary          int64
Department     object
Experience      int64
JoiningDate    object
dtype: object

In [37]:
display(
    json_df.isnull().sum()
)

CustomerID     0
Name           0
Age            0
Gender         0
City           0
Salary         0
Department     0
Experience     0
JoiningDate    0
dtype: int64

In [38]:
nested_data = {
    "employee": {
        "id": 101,
        "name": "Apuri",
        "department": {
            "name": "AI",
            "location": "Hyderabad"
        }
    }
}

display(
    pd.json_normalize(nested_data)
)

   employee.id employee.name employee.department.name employee.department.location
0          101         Apuri                       AI                    Hyderabad

In [39]:
try:

    pd.read_json(
        DATASET_DIR / "invalid.json"
    )

except FileNotFoundError as error:

    logger.error(error)

    print(error)

except ValueError as error:

    logger.error(error)

    print(error)

2026-07-01 23:32:20,523 | ERROR | File c:\Users\apuri\sprint2_dataset_loading\datasets\invalid.json does not exist

File c:\Users\apuri\sprint2_dataset_loading\datasets\invalid.json does not exist

In [40]:
logger.info("JSON module completed successfully.")

2026-07-01 23:32:38,653 | INFO | JSON module completed successfully.

In [41]:
with open(LOG_FILE, "r") as file:
    print(file.read())

2026-07-01 18:42:39,936 | INFO | Logging configured successfully.
2026-07-01 18:42:59,140 | INFO | Logging configured successfully.
2026-07-01 18:43:01,589 | INFO | Logging configured successfully.
2026-07-01 18:44:05,739 | INFO | Dataset loading started.
2026-07-01 18:44:05,741 | WARNING | This is a sample warning message.
2026-07-01 18:44:05,742 | ERROR | This is a sample error message.
2026-07-01 18:52:48,799 | ERROR | Dataset path does not exist.
2026-07-01 18:53:15,089 | ERROR | XML files are not supported.
2026-07-01 22:39:58,386 | INFO | CSV file found.
2026-07-01 22:40:28,126 | INFO | Loading CSV file.
2026-07-01 22:40:28,265 | INFO | CSV loaded successfully.
2026-07-01 22:43:29,945 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.csv'
2026-07-01 22:46:35,070 | INFO | Excel file found.
2026-07-01 22:46:53,669 | INFO | Loading Excel workbook.
2026-07-01 22:46:54,559 | INFO | Excel loaded successfully.
2026-07-01 22:49:42,200 | ERROR | Worksheet named 'InvalidSheet' not found
2026-07-01 22:50:05,446 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.xlsx'
2026-07-01 23:30:09,170 | INFO | JSON file found.
2026-07-01 23:30:30,713 | INFO | Loading JSON dataset.
2026-07-01 23:30:30,809 | INFO | JSON loaded successfully.
2026-07-01 23:32:20,523 | ERROR | File c:\Users\apuri\sprint2_dataset_loading\datasets\invalid.json does not exist
2026-07-01 23:32:38,653 | INFO | JSON module completed successfully.

## Module Summary

Successfully implemented:

- JSON loading
- Nested JSON handling
- File validation
- Missing file handling
- Invalid JSON handling
- Logging
- Exception handling

This implementation satisfies all JSON loading requirements specified in Sprint 2.

In [42]:
txt_file = DATASET_DIR / "employees.txt"

sample_text = """Employee Data

101,John,HR
102,Alice,Finance
103,Bob,Engineering
104,David,Marketing
"""

with open(txt_file, "w", encoding="utf-8") as file:
    file.write(sample_text)

print("Sample TXT file created successfully.")

Sample TXT file created successfully.

# Module 4 – Text File Loader

## Purpose

Text files are widely used for storing logs, configuration files, raw datasets, and system outputs.

This module demonstrates:

- Reading complete file content
- Reading files line by line
- Handling file encodings
- Logging
- Exception handling

In [43]:
if txt_file.exists():

    logger.info("TXT file found.")

    print("TXT file exists.")

else:

    logger.error("TXT file not found.")

    raise InvalidFilePathException(
        f"{txt_file} does not exist."
    )

2026-07-01 23:36:15,471 | INFO | TXT file found.

TXT file exists.

In [44]:
try:

    logger.info("Reading complete TXT file.")

    with open(txt_file, "r", encoding="utf-8") as file:

        content = file.read()

    print(content)

    logger.info("TXT file loaded successfully.")

except Exception as error:

    logger.error(error)

    raise

2026-07-01 23:36:33,822 | INFO | Reading complete TXT file.
2026-07-01 23:36:33,839 | INFO | TXT file loaded successfully.

Employee Data

101,John,HR
102,Alice,Finance
103,Bob,Engineering
104,David,Marketing

In [45]:
with open(txt_file, "r", encoding="utf-8") as file:

    for line_number, line in enumerate(file, start=1):

        print(f"Line {line_number}: {line.strip()}")

Line 1: Employee Data
Line 2:
Line 3: 101,John,HR
Line 4: 102,Alice,Finance
Line 5: 103,Bob,Engineering
Line 6: 104,David,Marketing

In [46]:
try:

    with open(
        txt_file,
        "r",
        encoding="utf-8"
    ) as file:

        print(file.readline())

except UnicodeDecodeError as error:

    logger.error(error)

    print(error)

Employee Data

In [47]:
try:

    with open(
        DATASET_DIR / "missing.txt",
        "r"
    ) as file:

        print(file.read())

except FileNotFoundError as error:

    logger.error(error)

    print(error)

2026-07-01 23:37:59,136 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.txt'

[Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.txt'

In [48]:
logger.info("TXT module completed successfully.")

2026-07-01 23:38:18,507 | INFO | TXT module completed successfully.

## Module Summary

Successfully implemented:

- Reading complete text files
- Reading line by line
- Encoding support
- File validation
- Logging
- Exception handling

This implementation satisfies all TXT file loading requirements specified in Sprint 2.

In [49]:
employees_df.to_csv("output.csv")
json_df.to_json("output.json")

# Module 5 – Dataset Writer

## Purpose

After loading and processing datasets, the next step in any data pipeline is to save the processed data.

This module demonstrates how to write datasets into multiple formats while maintaining reusable, modular, and readable code.

Supported Output Formats:

- CSV
- JSON
- Excel
- TXT
- Pickle

All writing operations are logged, validated, and protected with exception handling.

In [50]:
def save_csv(dataframe: pd.DataFrame,
             output_path: Path) -> None:
    """
    Save DataFrame as CSV.
    """

    try:

        logger.info(f"Saving CSV : {output_path}")

        dataframe.to_csv(
            output_path,
            index=False
        )

        logger.info("CSV saved successfully.")

    except Exception as error:

        logger.error(error)

        raise

In [51]:
def save_json(dataframe: pd.DataFrame,
              output_path: Path) -> None:
    """
    Save DataFrame as JSON.
    """

    try:

        logger.info(f"Saving JSON : {output_path}")

        dataframe.to_json(
            output_path,
            orient="records",
            indent=4
        )

        logger.info("JSON saved successfully.")

    except Exception as error:

        logger.error(error)

        raise

In [52]:
def save_excel(dataframe: pd.DataFrame,
               output_path: Path) -> None:
    """
    Save DataFrame as Excel.
    """

    try:

        logger.info(f"Saving Excel : {output_path}")

        dataframe.to_excel(
            output_path,
            index=False
        )

        logger.info("Excel saved successfully.")

    except Exception as error:

        logger.error(error)

        raise

In [53]:
def save_txt(dataframe: pd.DataFrame,
             output_path: Path) -> None:
    """
    Save DataFrame as TXT.
    """

    try:

        logger.info(f"Saving TXT : {output_path}")

        with open(
            output_path,
            "w",
            encoding="utf-8"
        ) as file:

            file.write(
                dataframe.to_string(
                    index=False
                )
            )

        logger.info("TXT saved successfully.")

    except Exception as error:

        logger.error(error)

        raise

In [54]:
def save_pickle(dataframe: pd.DataFrame,
                output_path: Path) -> None:
    """
    Save DataFrame as Pickle.
    """

    try:

        logger.info(f"Saving Pickle : {output_path}")

        with open(
            output_path,
            "wb"
        ) as file:

            pickle.dump(
                dataframe,
                file
            )

        logger.info("Pickle saved successfully.")

    except Exception as error:

        logger.error(error)

        raise

In [55]:
save_csv(
    employees_df,
    OUTPUT_DIR / "employees_output.csv"
)

save_json(
    employees_df,
    OUTPUT_DIR / "employees_output.json"
)

save_excel(
    employees_df,
    OUTPUT_DIR / "employees_output.xlsx"
)

save_txt(
    employees_df,
    OUTPUT_DIR / "employees_output.txt"
)

save_pickle(
    employees_df,
    OUTPUT_DIR / "employees_output.pkl"
)

print("All datasets saved successfully.")

2026-07-01 23:44:16,898 | INFO | Saving CSV : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.csv
2026-07-01 23:44:16,902 | INFO | CSV saved successfully.
2026-07-01 23:44:16,904 | INFO | Saving JSON : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.json
2026-07-01 23:44:16,908 | INFO | JSON saved successfully.
2026-07-01 23:44:16,909 | INFO | Saving Excel : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.xlsx
2026-07-01 23:44:17,020 | INFO | Excel saved successfully.
2026-07-01 23:44:17,021 | INFO | Saving TXT : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.txt
2026-07-01 23:44:17,031 | INFO | TXT saved successfully.
2026-07-01 23:44:17,032 | INFO | Saving Pickle : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.pkl
2026-07-01 23:44:17,036 | INFO | Pickle saved successfully.

All datasets saved successfully.

In [56]:
for file in OUTPUT_DIR.iterdir():
    print(file.name)

employees_output.csv
employees_output.json
employees_output.pkl
employees_output.txt
employees_output.xlsx

## Module Summary

Successfully implemented:

- Saving datasets as CSV
- Saving datasets as JSON
- Saving datasets as Excel
- Saving datasets as TXT
- Saving datasets as Pickle
- Logging every write operation
- Exception handling for file writing

This implementation satisfies all Dataset Writer requirements specified in Sprint 2.

# Module 6 – File Path Management

## Purpose

Managing file paths correctly is essential for building reusable and portable data pipelines.

Instead of hardcoding file locations throughout the notebook, reusable helper functions are created to:

- Validate file paths
- Create directories automatically
- Generate output filenames
- Work with both relative and absolute paths

Using `pathlib` improves readability and ensures compatibility across different operating systems.

In [57]:
def validate_file_path(file_path: Path) -> bool:
    """
    Validate whether the file exists.

    Parameters
    ----------
    file_path : Path
        Path of the input file.

    Returns
    -------
    bool
        True if file exists.

    Raises
    ------
    InvalidFilePathException
        If file does not exist.
    """

    if not file_path.exists():

        logger.error(f"File not found : {file_path}")

        raise InvalidFilePathException(
            f"{file_path} does not exist."
        )

    logger.info(f"Validated file : {file_path}")

    return True

In [58]:
validate_file_path(csv_file)

2026-07-01 23:47:13,173 | INFO | Validated file : c:\Users\apuri\sprint2_dataset_loading\datasets\employees.csv

True

In [59]:
def create_directory(directory: Path) -> None:
    """
    Create directory if it does not exist.
    """

    directory.mkdir(
        parents=True,
        exist_ok=True
    )

    logger.info(f"Directory verified : {directory}")

In [60]:
create_directory(OUTPUT_DIR)

print("Directory Ready")

2026-07-01 23:47:48,148 | INFO | Directory verified : c:\Users\apuri\sprint2_dataset_loading\outputs

Directory Ready

In [62]:
from datetime import datetime

def generate_output_filename(
    prefix: str,
    extension: str
) -> Path:
    """
    Generate output filename with timestamp.
    """

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    filename = (
        f"{prefix}_{timestamp}.{extension}"
    )

    return OUTPUT_DIR / filename

In [63]:
generate_output_filename(
    "employees",
    "csv"
)

WindowsPath('c:/Users/apuri/sprint2_dataset_loading/outputs/employees_20260702_002057.csv')

In [64]:
relative_path = Path("datasets") / "employees.csv"

print(relative_path)

datasets\employees.csv

In [65]:
absolute_path = relative_path.resolve()

print(absolute_path)

C:\Users\apuri\sprint2_dataset_loading\notebooks\datasets\employees.csv

## Relative vs Absolute Paths

Relative Path

In [66]:
print(validate_file_path(csv_file))

create_directory(OUTPUT_DIR)

print(generate_output_filename(
    "employees",
    "json"
))

2026-07-02 00:26:40,051 | INFO | Validated file : c:\Users\apuri\sprint2_dataset_loading\datasets\employees.csv
2026-07-02 00:26:40,053 | INFO | Directory verified : c:\Users\apuri\sprint2_dataset_loading\outputs

True
c:\Users\apuri\sprint2_dataset_loading\outputs\employees_20260702_002640.json

# Module 7 – Logging Integration

## Purpose

Logging is integrated throughout the notebook to monitor every important activity.

Instead of logging only errors, the notebook records the complete execution lifecycle including:

- Dataset loading
- Dataset writing
- Directory creation
- File validation
- Warning messages
- Exceptions

This provides complete execution traceability and simplifies debugging.

In [67]:
logger.info(...)

2026-07-02 01:42:36,340 | INFO | Ellipsis

In [68]:
def log_start(operation: str):

    logger.info("=" * 60)

    logger.info(f"STARTED : {operation}")

    logger.info("=" * 60)


def log_success(operation: str):

    logger.info(f"SUCCESS : {operation}")


def log_warning(message: str):

    logger.warning(message)


def log_error(error):

    logger.error(error)

In [69]:
logger.info("Loading CSV")

2026-07-02 01:43:35,020 | INFO | Loading CSV

In [70]:
log_start("CSV Loading")

employees_df = pd.read_csv(csv_file)

log_success("CSV Loading")

2026-07-02 01:43:51,701 | INFO | ============================================================
2026-07-02 01:43:51,703 | INFO | STARTED : CSV Loading
2026-07-02 01:43:51,704 | INFO | ============================================================
2026-07-02 01:43:51,720 | INFO | SUCCESS : CSV Loading

In [71]:
log_start("Excel Loading")

excel_df = pd.read_excel(excel_file)

log_success("Excel Loading")

2026-07-02 01:44:11,462 | INFO | ============================================================
2026-07-02 01:44:11,463 | INFO | STARTED : Excel Loading
2026-07-02 01:44:11,465 | INFO | ============================================================
2026-07-02 01:44:11,537 | INFO | SUCCESS : Excel Loading

In [72]:
log_start("JSON Loading")

json_df = pd.read_json(json_file)

log_success("JSON Loading")

2026-07-02 01:44:25,432 | INFO | ============================================================
2026-07-02 01:44:25,433 | INFO | STARTED : JSON Loading
2026-07-02 01:44:25,435 | INFO | ============================================================
2026-07-02 01:44:25,453 | INFO | SUCCESS : JSON Loading

In [73]:
log_start("TXT Loading")

with open(txt_file) as file:

    text = file.read()

log_success("TXT Loading")

2026-07-02 01:44:40,171 | INFO | ============================================================
2026-07-02 01:44:40,173 | INFO | STARTED : TXT Loading
2026-07-02 01:44:40,174 | INFO | ============================================================
2026-07-02 01:44:40,177 | INFO | SUCCESS : TXT Loading

In [79]:
log_start("Saving CSV")

save_csv(
    employees_df,
    OUTPUT_DIR / "employees_output.csv"
)

log_success("Saving CSV")

2026-07-02 01:49:30,134 | INFO | ============================================================
2026-07-02 01:49:30,137 | INFO | STARTED : Saving CSV
2026-07-02 01:49:30,139 | INFO | ============================================================
2026-07-02 01:49:30,142 | INFO | Saving CSV : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.csv
2026-07-02 01:49:30,147 | INFO | CSV saved successfully.
2026-07-02 01:49:30,149 | INFO | SUCCESS : Saving CSV

In [80]:
log_start("Saving JSON")

save_json(
    employees_df,
    OUTPUT_DIR / "employees_output.json"
)

log_success("Saving JSON")

2026-07-02 01:50:13,111 | INFO | ============================================================
2026-07-02 01:50:13,116 | INFO | STARTED : Saving JSON
2026-07-02 01:50:13,120 | INFO | ============================================================
2026-07-02 01:50:13,123 | INFO | Saving JSON : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.json
2026-07-02 01:50:13,126 | INFO | JSON saved successfully.
2026-07-02 01:50:13,128 | INFO | SUCCESS : Saving JSON

In [81]:
log_start("Saving Excel")

save_excel(
    employees_df,
    OUTPUT_DIR / "employees_output.xlsx"
)

log_success("Saving Excel")

2026-07-02 01:50:32,586 | INFO | ============================================================
2026-07-02 01:50:32,587 | INFO | STARTED : Saving Excel
2026-07-02 01:50:32,588 | INFO | ============================================================
2026-07-02 01:50:32,591 | INFO | Saving Excel : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.xlsx
2026-07-02 01:50:32,692 | INFO | Excel saved successfully.
2026-07-02 01:50:32,693 | INFO | SUCCESS : Saving Excel

In [82]:
log_start("Saving TXT")

save_txt(
    employees_df,
    OUTPUT_DIR / "employees_output.txt"
)

log_success("Saving TXT")

2026-07-02 01:50:48,331 | INFO | ============================================================
2026-07-02 01:50:48,332 | INFO | STARTED : Saving TXT
2026-07-02 01:50:48,333 | INFO | ============================================================
2026-07-02 01:50:48,337 | INFO | Saving TXT : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.txt
2026-07-02 01:50:48,351 | INFO | TXT saved successfully.
2026-07-02 01:50:48,353 | INFO | SUCCESS : Saving TXT

In [83]:
log_start("Saving Pickle")

save_pickle(
    employees_df,
    OUTPUT_DIR / "employees_output.pkl"
)

log_success("Saving Pickle")

2026-07-02 01:51:06,039 | INFO | ============================================================
2026-07-02 01:51:06,041 | INFO | STARTED : Saving Pickle
2026-07-02 01:51:06,043 | INFO | ============================================================
2026-07-02 01:51:06,044 | INFO | Saving Pickle : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.pkl
2026-07-02 01:51:06,049 | INFO | Pickle saved successfully.
2026-07-02 01:51:06,051 | INFO | SUCCESS : Saving Pickle

In [84]:
def save_all_formats(dataframe: pd.DataFrame):
    """
    Save a dataset in all supported formats.
    """

    save_operations = [
        ("CSV", save_csv, OUTPUT_DIR / "employees_output.csv"),
        ("JSON", save_json, OUTPUT_DIR / "employees_output.json"),
        ("Excel", save_excel, OUTPUT_DIR / "employees_output.xlsx"),
        ("TXT", save_txt, OUTPUT_DIR / "employees_output.txt"),
        ("Pickle", save_pickle, OUTPUT_DIR / "employees_output.pkl"),
    ]

    for name, writer_function, output_path in save_operations:
        log_start(f"Saving {name}")

        writer_function(dataframe, output_path)

        log_success(f"Saving {name}")

    print("All datasets saved successfully.")

In [85]:
save_all_formats(employees_df)

2026-07-02 01:52:03,085 | INFO | ============================================================
2026-07-02 01:52:03,088 | INFO | STARTED : Saving CSV
2026-07-02 01:52:03,094 | INFO | ============================================================
2026-07-02 01:52:03,096 | INFO | Saving CSV : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.csv
2026-07-02 01:52:03,100 | INFO | CSV saved successfully.
2026-07-02 01:52:03,102 | INFO | SUCCESS : Saving CSV
2026-07-02 01:52:03,103 | INFO | ============================================================
2026-07-02 01:52:03,104 | INFO | STARTED : Saving JSON
2026-07-02 01:52:03,105 | INFO | ============================================================
2026-07-02 01:52:03,106 | INFO | Saving JSON : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.json
2026-07-02 01:52:03,109 | INFO | JSON saved successfully.
2026-07-02 01:52:03,110 | INFO | SUCCESS : Saving JSON
2026-07-02 01:52:03,111 | INFO | ============================================================
2026-07-02 01:52:03,112 | INFO | STARTED : Saving Excel
2026-07-02 01:52:03,113 | INFO | ============================================================
2026-07-02 01:52:03,114 | INFO | Saving Excel : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.xlsx
2026-07-02 01:52:03,222 | INFO | Excel saved successfully.
2026-07-02 01:52:03,223 | INFO | SUCCESS : Saving Excel
2026-07-02 01:52:03,225 | INFO | ============================================================
2026-07-02 01:52:03,226 | INFO | STARTED : Saving TXT
2026-07-02 01:52:03,227 | INFO | ============================================================
2026-07-02 01:52:03,229 | INFO | Saving TXT : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.txt
2026-07-02 01:52:03,241 | INFO | TXT saved successfully.
2026-07-02 01:52:03,242 | INFO | SUCCESS : Saving TXT
2026-07-02 01:52:03,245 | INFO | ============================================================
2026-07-02 01:52:03,248 | INFO | STARTED : Saving Pickle
2026-07-02 01:52:03,250 | INFO | ============================================================
2026-07-02 01:52:03,251 | INFO | Saving Pickle : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.pkl
2026-07-02 01:52:03,255 | INFO | Pickle saved successfully.
2026-07-02 01:52:03,258 | INFO | SUCCESS : Saving Pickle

All datasets saved successfully.

# Module 8 – Exception Handling Demonstration

## Purpose

Exception handling is implemented throughout the notebook to ensure that unexpected situations are handled gracefully.

This module demonstrates:

- Missing files
- Invalid worksheet names
- Invalid JSON
- Invalid output paths
- Proper use of try, except, finally, and raise

All exceptions are logged to the application log and displayed with meaningful messages.

In [86]:
try:

    missing_csv = DATASET_DIR / "missing.csv"

    validate_file_path(missing_csv)

    pd.read_csv(missing_csv)

except InvalidFilePathException as error:

    logger.error(error)

    print(error)

finally:

    print("CSV validation completed.")

2026-07-02 01:53:11,423 | ERROR | File not found : c:\Users\apuri\sprint2_dataset_loading\datasets\missing.csv
2026-07-02 01:53:11,426 | ERROR | c:\Users\apuri\sprint2_dataset_loading\datasets\missing.csv does not exist.

c:\Users\apuri\sprint2_dataset_loading\datasets\missing.csv does not exist.
CSV validation completed.

In [87]:
try:

    pd.read_excel(
        excel_file,
        sheet_name="UnknownSheet"
    )

except ValueError as error:

    logger.error(error)

    print(error)

finally:

    print("Worksheet validation completed.")

2026-07-02 01:53:37,185 | ERROR | Worksheet named 'UnknownSheet' not found

Worksheet named 'UnknownSheet' not found
Worksheet validation completed.

In [88]:
try:

    pd.read_json(
        DATASET_DIR / "invalid.json"
    )

except Exception as error:

    logger.error(error)

    print(error)

finally:

    print("JSON validation completed.")

2026-07-02 01:53:58,211 | ERROR | File c:\Users\apuri\sprint2_dataset_loading\datasets\invalid.json does not exist

File c:\Users\apuri\sprint2_dataset_loading\datasets\invalid.json does not exist
JSON validation completed.

In [89]:
try:

    with open(
        DATASET_DIR / "missing.txt",
        "r"
    ) as file:

        print(file.read())

except FileNotFoundError as error:

    logger.error(error)

    print(error)

finally:

    print("TXT validation completed.")

2026-07-02 01:54:18,146 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.txt'

[Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.txt'
TXT validation completed.

In [90]:
try:

    invalid_path = Path(
        "Z:/Invalid/Folder/output.csv"
    )

    employees_df.to_csv(
        invalid_path
    )

except Exception as error:

    logger.error(error)

    print(error)

finally:

    print("Output validation completed.")

2026-07-02 01:54:39,339 | ERROR | Cannot save file into a non-existent directory: 'Z:\Invalid\Folder'

Cannot save file into a non-existent directory: 'Z:\Invalid\Folder'
Output validation completed.

In [91]:
try:

    file_path = DATASET_DIR / "dummy.xml"

    if file_path.suffix != ".csv":

        raise UnsupportedFileFormatException(
            "Only CSV files are supported."
        )

except UnsupportedFileFormatException as error:

    logger.error(error)

    print(error)

2026-07-02 01:54:55,872 | ERROR | Only CSV files are supported.

Only CSV files are supported.

In [92]:
import traceback

try:

    validate_file_path(
        DATASET_DIR / "unknown.csv"
    )

except Exception:

    logger.exception(
        "Complete exception details"
    )

    traceback.print_exc()

2026-07-02 01:55:11,417 | ERROR | File not found : c:\Users\apuri\sprint2_dataset_loading\datasets\unknown.csv
2026-07-02 01:55:11,419 | ERROR | Complete exception details
Traceback (most recent call last):
  File "C:\Users\apuri\AppData\Local\Temp\ipykernel_15416\1885703500.py", line 5, in <module>
    validate_file_path(
    ~~~~~~~~~~~~~~~~~~^
        DATASET_DIR / "unknown.csv"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\apuri\AppData\Local\Temp\ipykernel_15416\2396373911.py", line 25, in validate_file_path
    raise InvalidFilePathException(
        f"{file_path} does not exist."
    )
InvalidFilePathException: c:\Users\apuri\sprint2_dataset_loading\datasets\unknown.csv does not exist.
Traceback (most recent call last):
  File "C:\Users\apuri\AppData\Local\Temp\ipykernel_15416\1885703500.py", line 5, in <module>
    validate_file_path(
    ~~~~~~~~~~~~~~~~~~^
        DATASET_DIR / "unknown.csv"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\apuri\AppData\Local\Temp\ipykernel_15416\2396373911.py", line 25, in validate_file_path
    raise InvalidFilePathException(
        f"{file_path} does not exist."
    )
InvalidFilePathException: c:\Users\apuri\sprint2_dataset_loading\datasets\unknown.csv does not exist.

In [93]:
with open(LOG_FILE) as file:

    print(file.read())

2026-07-01 18:42:39,936 | INFO | Logging configured successfully.
2026-07-01 18:42:59,140 | INFO | Logging configured successfully.
2026-07-01 18:43:01,589 | INFO | Logging configured successfully.
2026-07-01 18:44:05,739 | INFO | Dataset loading started.
2026-07-01 18:44:05,741 | WARNING | This is a sample warning message.
2026-07-01 18:44:05,742 | ERROR | This is a sample error message.
2026-07-01 18:52:48,799 | ERROR | Dataset path does not exist.
2026-07-01 18:53:15,089 | ERROR | XML files are not supported.
2026-07-01 22:39:58,386 | INFO | CSV file found.
2026-07-01 22:40:28,126 | INFO | Loading CSV file.
2026-07-01 22:40:28,265 | INFO | CSV loaded successfully.
2026-07-01 22:43:29,945 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.csv'
2026-07-01 22:46:35,070 | INFO | Excel file found.
2026-07-01 22:46:53,669 | INFO | Loading Excel workbook.
2026-07-01 22:46:54,559 | INFO | Excel loaded successfully.
2026-07-01 22:49:42,200 | ERROR | Worksheet named 'InvalidSheet' not found
2026-07-01 22:50:05,446 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.xlsx'
2026-07-01 23:30:09,170 | INFO | JSON file found.
2026-07-01 23:30:30,713 | INFO | Loading JSON dataset.
2026-07-01 23:30:30,809 | INFO | JSON loaded successfully.
2026-07-01 23:32:20,523 | ERROR | File c:\Users\apuri\sprint2_dataset_loading\datasets\invalid.json does not exist
2026-07-01 23:32:38,653 | INFO | JSON module completed successfully.
2026-07-01 23:36:15,471 | INFO | TXT file found.
2026-07-01 23:36:33,822 | INFO | Reading complete TXT file.
2026-07-01 23:36:33,839 | INFO | TXT file loaded successfully.
2026-07-01 23:37:59,136 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.txt'
2026-07-01 23:38:18,507 | INFO | TXT module completed successfully.
2026-07-01 23:44:16,898 | INFO | Saving CSV : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.csv
2026-07-01 23:44:16,902 | INFO | CSV saved successfully.
2026-07-01 23:44:16,904 | INFO | Saving JSON : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.json
2026-07-01 23:44:16,908 | INFO | JSON saved successfully.
2026-07-01 23:44:16,909 | INFO | Saving Excel : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.xlsx
2026-07-01 23:44:17,020 | INFO | Excel saved successfully.
2026-07-01 23:44:17,021 | INFO | Saving TXT : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.txt
2026-07-01 23:44:17,031 | INFO | TXT saved successfully.
2026-07-01 23:44:17,032 | INFO | Saving Pickle : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.pkl
2026-07-01 23:44:17,036 | INFO | Pickle saved successfully.
2026-07-01 23:47:13,173 | INFO | Validated file : c:\Users\apuri\sprint2_dataset_loading\datasets\employees.csv
2026-07-01 23:47:48,148 | INFO | Directory verified : c:\Users\apuri\sprint2_dataset_loading\outputs
2026-07-02 00:26:40,051 | INFO | Validated file : c:\Users\apuri\sprint2_dataset_loading\datasets\employees.csv
2026-07-02 00:26:40,053 | INFO | Directory verified : c:\Users\apuri\sprint2_dataset_loading\outputs
2026-07-02 01:42:36,340 | INFO | Ellipsis
2026-07-02 01:43:35,020 | INFO | Loading CSV
2026-07-02 01:43:51,701 | INFO | ============================================================
2026-07-02 01:43:51,703 | INFO | STARTED : CSV Loading
2026-07-02 01:43:51,704 | INFO | ============================================================
2026-07-02 01:43:51,720 | INFO | SUCCESS : CSV Loading
2026-07-02 01:44:11,462 | INFO | ============================================================
2026-07-02 01:44:11,463 | INFO | STARTED : Excel Loading
2026-07-02 01:44:11,465 | INFO | ============================================================
2026-07-02 01:44:11,537 | INFO | SUCCESS : Excel Loading
2026-07-02 01:44:25,432 | INFO | ============================================================
2026-07-02 01:44:25,433 | INFO | STARTED : JSON Loading
2026-07-02 01:44:25,435 | INFO | ============================================================
2026-07-02 01:44:25,453 | INFO | SUCCESS : JSON Loading
2026-07-02 01:44:40,171 | INFO | ============================================================
2026-07-02 01:44:40,173 | INFO | STARTED : TXT Loading
2026-07-02 01:44:40,174 | INFO | ============================================================
2026-07-02 01:44:40,177 | INFO | SUCCESS : TXT Loading
2026-07-02 01:44:55,710 | INFO | Saving CSV
2026-07-02 01:45:08,596 | INFO | ============================================================
2026-07-02 01:45:08,597 | INFO | STARTED : Saving CSV
2026-07-02 01:45:08,599 | INFO | ============================================================
2026-07-02 01:48:10,425 | INFO | ============================================================
2026-07-02 01:48:10,432 | INFO | STARTED : Saving CSV
2026-07-02 01:48:10,434 | INFO | ============================================================
2026-07-02 01:48:59,520 | INFO | ============================================================
2026-07-02 01:48:59,521 | INFO | STARTED : Saving CSV
2026-07-02 01:48:59,524 | INFO | ============================================================
2026-07-02 01:49:19,458 | INFO | ============================================================
2026-07-02 01:49:19,459 | INFO | STARTED : Saving CSV
2026-07-02 01:49:19,461 | INFO | ============================================================
2026-07-02 01:49:19,462 | INFO | Saving CSV : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.csv
2026-07-02 01:49:19,469 | INFO | CSV saved successfully.
2026-07-02 01:49:19,471 | INFO | SUCCESS : Saving CSV
2026-07-02 01:49:30,134 | INFO | ============================================================
2026-07-02 01:49:30,137 | INFO | STARTED : Saving CSV
2026-07-02 01:49:30,139 | INFO | ============================================================
2026-07-02 01:49:30,142 | INFO | Saving CSV : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.csv
2026-07-02 01:49:30,147 | INFO | CSV saved successfully.
2026-07-02 01:49:30,149 | INFO | SUCCESS : Saving CSV
2026-07-02 01:50:13,111 | INFO | ============================================================
2026-07-02 01:50:13,116 | INFO | STARTED : Saving JSON
2026-07-02 01:50:13,120 | INFO | ============================================================
2026-07-02 01:50:13,123 | INFO | Saving JSON : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.json
2026-07-02 01:50:13,126 | INFO | JSON saved successfully.
2026-07-02 01:50:13,128 | INFO | SUCCESS : Saving JSON
2026-07-02 01:50:32,586 | INFO | ============================================================
2026-07-02 01:50:32,587 | INFO | STARTED : Saving Excel
2026-07-02 01:50:32,588 | INFO | ============================================================
2026-07-02 01:50:32,591 | INFO | Saving Excel : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.xlsx
2026-07-02 01:50:32,692 | INFO | Excel saved successfully.
2026-07-02 01:50:32,693 | INFO | SUCCESS : Saving Excel
2026-07-02 01:50:48,331 | INFO | ============================================================
2026-07-02 01:50:48,332 | INFO | STARTED : Saving TXT
2026-07-02 01:50:48,333 | INFO | ============================================================
2026-07-02 01:50:48,337 | INFO | Saving TXT : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.txt
2026-07-02 01:50:48,351 | INFO | TXT saved successfully.
2026-07-02 01:50:48,353 | INFO | SUCCESS : Saving TXT
2026-07-02 01:51:06,039 | INFO | ============================================================
2026-07-02 01:51:06,041 | INFO | STARTED : Saving Pickle
2026-07-02 01:51:06,043 | INFO | ============================================================
2026-07-02 01:51:06,044 | INFO | Saving Pickle : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.pkl
2026-07-02 01:51:06,049 | INFO | Pickle saved successfully.
2026-07-02 01:51:06,051 | INFO | SUCCESS : Saving Pickle
2026-07-02 01:52:03,085 | INFO | ============================================================
2026-07-02 01:52:03,088 | INFO | STARTED : Saving CSV
2026-07-02 01:52:03,094 | INFO | ============================================================
2026-07-02 01:52:03,096 | INFO | Saving CSV : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.csv
2026-07-02 01:52:03,100 | INFO | CSV saved successfully.
2026-07-02 01:52:03,102 | INFO | SUCCESS : Saving CSV
2026-07-02 01:52:03,103 | INFO | ============================================================
2026-07-02 01:52:03,104 | INFO | STARTED : Saving JSON
2026-07-02 01:52:03,105 | INFO | ============================================================
2026-07-02 01:52:03,106 | INFO | Saving JSON : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.json
2026-07-02 01:52:03,109 | INFO | JSON saved successfully.
2026-07-02 01:52:03,110 | INFO | SUCCESS : Saving JSON
2026-07-02 01:52:03,111 | INFO | ============================================================
2026-07-02 01:52:03,112 | INFO | STARTED : Saving Excel
2026-07-02 01:52:03,113 | INFO | ============================================================
2026-07-02 01:52:03,114 | INFO | Saving Excel : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.xlsx
2026-07-02 01:52:03,222 | INFO | Excel saved successfully.
2026-07-02 01:52:03,223 | INFO | SUCCESS : Saving Excel
2026-07-02 01:52:03,225 | INFO | ============================================================
2026-07-02 01:52:03,226 | INFO | STARTED : Saving TXT
2026-07-02 01:52:03,227 | INFO | ============================================================
2026-07-02 01:52:03,229 | INFO | Saving TXT : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.txt
2026-07-02 01:52:03,241 | INFO | TXT saved successfully.
2026-07-02 01:52:03,242 | INFO | SUCCESS : Saving TXT
2026-07-02 01:52:03,245 | INFO | ============================================================
2026-07-02 01:52:03,248 | INFO | STARTED : Saving Pickle
2026-07-02 01:52:03,250 | INFO | ============================================================
2026-07-02 01:52:03,251 | INFO | Saving Pickle : c:\Users\apuri\sprint2_dataset_loading\outputs\employees_output.pkl
2026-07-02 01:52:03,255 | INFO | Pickle saved successfully.
2026-07-02 01:52:03,258 | INFO | SUCCESS : Saving Pickle
2026-07-02 01:53:11,423 | ERROR | File not found : c:\Users\apuri\sprint2_dataset_loading\datasets\missing.csv
2026-07-02 01:53:11,426 | ERROR | c:\Users\apuri\sprint2_dataset_loading\datasets\missing.csv does not exist.
2026-07-02 01:53:37,185 | ERROR | Worksheet named 'UnknownSheet' not found
2026-07-02 01:53:58,211 | ERROR | File c:\Users\apuri\sprint2_dataset_loading\datasets\invalid.json does not exist
2026-07-02 01:54:18,146 | ERROR | [Errno 2] No such file or directory: 'c:\\Users\\apuri\\sprint2_dataset_loading\\datasets\\missing.txt'
2026-07-02 01:54:39,339 | ERROR | Cannot save file into a non-existent directory: 'Z:\Invalid\Folder'
2026-07-02 01:54:55,872 | ERROR | Only CSV files are supported.
2026-07-02 01:55:11,417 | ERROR | File not found : c:\Users\apuri\sprint2_dataset_loading\datasets\unknown.csv
2026-07-02 01:55:11,419 | ERROR | Complete exception details
Traceback (most recent call last):
  File "C:\Users\apuri\AppData\Local\Temp\ipykernel_15416\1885703500.py", line 5, in <module>
    validate_file_path(
    ~~~~~~~~~~~~~~~~~~^
        DATASET_DIR / "unknown.csv"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\apuri\AppData\Local\Temp\ipykernel_15416\2396373911.py", line 25, in validate_file_path
    raise InvalidFilePathException(
        f"{file_path} does not exist."
    )
InvalidFilePathException: c:\Users\apuri\sprint2_dataset_loading\datasets\unknown.csv does not exist.

## Module Summary

Successfully demonstrated:

- try
- except
- finally
- raise
- Custom exceptions
- Graceful failure
- Complete exception logging

The notebook now satisfies all exception handling requirements defined in Sprint 2.

# Conclusion

In this sprint, a reusable dataset loading utility was developed using Python and Jupyter Notebook.

The notebook successfully demonstrates:

- Loading datasets from CSV, Excel, JSON, and TXT formats
- Writing datasets to multiple output formats
- File path validation
- Logging implementation
- Custom exception handling
- Modular and reusable code
- Software engineering best practices

This notebook provides a strong foundation for the next stages of the AI/ML pipeline, including data preprocessing, feature engineering, and machine learning.

# Key Learnings

Through this sprint, the following concepts were strengthened:

- Dataset loading using Pandas
- Working with multiple file formats
- File handling using pathlib
- Logging and debugging
- Exception handling
- Writing reusable functions
- Notebook documentation using Markdown
- Following PEP-8 coding standards
- Organizing code into logical modules

# Future Enhancements

If this notebook were extended into a production project, the following improvements could be implemented:

- Docker support
- CI/CD pipeline
- Environment-based configuration
- Database integration
- Cloud storage support (AWS S3, Azure Blob)
- Support for additional formats such as XML, SQL, and Avro
- Parallel dataset loading
- Automated unit testing